import { IShipments } from '@/utils/types';
import mongoose from 'mongoose';
import paginate from 'mongoose-paginate-v2';

// add DB error handling
export const ShipmentsSchema = new mongoose.Schema(
  {
    // the one that is set by the original shipper of the item for example DHL
    isn: {
      type: String,
      lowercase: true,
    },
    // the one that is generated by this system aka tracking number
    esn: {
      type: String,
      lowercase: true,
    },
    // this refers to customer shipping number aka TIP-0000
    csn: {
      type: String,
      required: true,
      lowercase: true,
    },
    isDomestic: {
      type: Boolean,
      required: false,
    },
    size: {
      weight: {
        type: Number,
        lowercase: true,
      },
      height: {
        type: Number,
        lowercase: true,
      },
      width: {
        type: Number,
        lowercase: true,
      },
      length: {
        type: Number,
        lowercase: true,
      },
    },
    shipmentDestination: {
      type: String,
      required: true,
      lowercase: true,
    },
    shippingMethod: {
      type: String,
      required: true,
      lowercase: true,
    },
    extraCosts: {
      type: Number,
      lowercase: true,
    },
    note: {
      type: String,
      lowercase: true,
    },
    status: {
      type: String,
      required: true,
      lowercase: true,
    },
    estimatedArrival: {
      type: Date,
    },
  },
  {
    timestamps: true,
  }
);

ShipmentsSchema.plugin(paginate);

interface ShipmentDocument extends mongoose.Document, IShipments {}

const ShipmentsCollection = mongoose.model<ShipmentDocument, mongoose.PaginateModel<ShipmentDocument>>(
  'Shipments',
  ShipmentsSchema,
  'shipments'
);
export default ShipmentsCollection;
